server:
  datasources:
    default:
      driver-class-name: "org.apache.derby.jdbc.EmbeddedDriver"
      jdbc-url: "jdbc:derby:output/testDB;create=true"
      username: "sa"
      password: "sa"

      connection-timeout-in-ms: 501
      login-timout-in-seconds: 11
      acquire-retry-delay-in-ms: 1001
      acquire-retry-attempt: 4

      connection-idle-limit-in-seconds: 16
      validate-timeout-in-seconds: 4

      log-query-execution-longer-than-ms: 81
      log-large-resultset: 501
      log-connection-longer-than-ms: 101
      statement-cache-max-size: 10
      reducer-time-interval-in-seconds: 61
      reducer-samples: 21

    h2:
      driver-class-name: "org.apache.derby.jdbc.EmbeddedDriver"
      jdbc-url: "jdbc:derby:output/testDB;create=true"
      username: "sa"
      password: "sa"

      pool-initial-size: 11
      pool-max-size: 101
      pool-fair: false
      pool-enable-connection-tracking: true

      log-stacktrace-for-long-query-execution: false
      log-stacktrace-for-large-resultset: false
      clear-sql-warnings: true
      reset-defaults-after-use: true
      default-auto-commit: false
      default-read-only: true

      pool-reducer-class: "org.vibur.dbcp.pool.PoolReducer"

    unit-test:
      driver-class-name: "org.apache.derby.jdbc.EmbeddedDriver"
      jdbc-url: "jdbc:derby:tests-resources/unit-test.db"
      username: "admin"
      password: "admin"

  auth:
    db-auth:
      datasource: "unit-test"
      select-user-password: "SELECT password FROM users WHERE username = ?"
      select-user-roles: "SELECT role_name FROM user_roles WHERE username = ?"