package kikaha.core.modules.security;

import io.undertow.server.HttpServerExchange;

public abstract class AbstractCookieSessionStore implements SessionStore {

	protected final SessionCookie cookie = new SessionCookie( "JSESSIONID" );

	/**
	 * Attempt to extract the sessionId from the current request. If no sessionId is
	 * present, a new one will be generated by the {@link AbstractCookieSessionStore#createNewSessionId} method.
	 *
	 * @param exchange
	 * @return
	 */
	protected String retrieveSessionIdFrom( HttpServerExchange exchange ){
		return cookie.retrieveSessionIdFrom( exchange, this::createNewSessionId );
	}

	/**
	 * Retrieve the {@link Session}, identified by the {@code sessionId}, from the storage.
	 *
	 * @param sessionId
	 * @return
	 */
	protected abstract Session getSessionFromCache(String sessionId);

	/**
	 * If no {@link Session} was not found at the storage, it will create a new one
	 * and store it for further usage. It was designed on a CAS style to avoid lock
	 * the register assigned to the {@code sessionId} for a long time.
	 *
	 * @param sessionId
	 * @param exchange
	 * @return
	 */
	protected Session tryToCreateAndStoreNewSession(String sessionId, HttpServerExchange exchange ){
		Session session = getSessionFromCache(sessionId);
		if (session == null)
			session = createAndStoreNewSession(sessionId, exchange);
		return session;
	}

	/**
	 * Create a new {@link Session} and store it at the main storage.
	 *
	 * @param sessionId
	 * @param exchange
	 * @return
	 */
	protected Session createAndStoreNewSession(String sessionId, HttpServerExchange exchange ){
		Session session = new DefaultSession( sessionId );
		storeSession(session.getId(), session);
		cookie.attachSessionCookie(exchange, session.getId());
		return session;
	}

	/**
	 * Store a {@link Session} at the storage.
	 *
	 * @param sessionId the identifier used to retrieve this same {@link Session}
	 * @param session
	 */
	protected abstract void storeSession(String sessionId, Session session);

	/**
	 * Generates a new SessionId for further usage.
	 * @return
	 */
	protected String createNewSessionId() {
		return SessionIdGenerator.generate();
	}
}
